# Generated by Django 5.2.4 on 2025-07-25 10:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('MEN', 'Men'), ('WOMEN', 'Women')], max_length=10)),
                ('category', models.CharField(max_length=50)),
                ('profile', models.CharField(choices=[('front', 'Front'), ('full', 'Full'), ('additional', 'Additional'), ('side', 'Side'), ('back', 'Back')], max_length=20)),
                ('image', models.ImageField(upload_to='uploads/')),
                ('same_profile', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
