# Generated by Django 5.2.4 on 2025-07-25 13:09

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_upload_is_multiple'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='category',
            field=models.CharField(choices=[('Blouses_Shirts', 'Blouses & Shirts'), ('Cardigans', 'Cardigans'), ('Denim', 'Denim'), ('Dresses', 'Dresses'), ('Graphic_Tees', 'Graphic Tees'), ('Jackets_Coats', 'Jackets & Coats'), ('Leggings', 'Leggings'), ('Pants', 'Pants'), ('Rompers_Jumpsuits', 'Rompers & Jumpsuits'), ('Shorts', 'Shorts'), ('Skirts', 'Skirts'), ('Sweaters', 'Sweaters'), ('Sweatshirts_Hoodies', 'Sweatshirts & Hoodies'), ('Tees_Tanks', 'Tees & Tanks')], max_length=50),
        ),
        migrations.AlterField(
            model_name='upload',
            name='image',
            field=models.ImageField(upload_to=api.models.custom_upload_to),
        ),
    ]
